remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Bitcoin KeyHunt
description: A visual hunt for 32 BTC puzzle keys

show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
